added simple api
GeorgeSokolovsky/internship-crm-back pull request #2
Opened 2019-02-19 09:35 UTC by stepanoves

2019-02-19 10:17 UTC, KKurchavy commented on src/app.module.ts
> +  imports: [MongooseModule.forRoot(`mongodb://${dbconfig.dbuser}:${dbconfig.dbpassword}@ds141815.mlab.com:41815/internship-crm`), NewsModule],
Почему бы не вынести url в отдельный объект(или класс) конфига, с методом для получения полной ссылки?

2019-02-19 10:19 UTC, KKurchavy commented on src/news/schemas/news.schema.ts
> +import * as mongoose from 'mongoose';
Можно подтянуть только "Schema", всё равно тут от монгуса больше ничего не используется

2019-02-19 11:18 UTC, GeorgeSokolovsky requested changes

2019-02-19 11:18 UTC, GeorgeSokolovsky commented on src/app.module.ts
> +  imports: [MongooseModule.forRoot(`mongodb://${dbconfig.dbuser}:${dbconfig.dbpassword}@ds141815.mlab.com:41815/internship-crm`), NewsModule],
https://docs.nestjs.com/techniques/mongodb
Посмотри как сделать через `forRootAsync` и `ConfigsService`.

2019-02-19 11:18 UTC, GeorgeSokolovsky commented on src/news/news.service.ts
> +    constructor(@InjectModel('News') private readonly newsModel: Model<News>) {}
Я за то, чтобы назвать модель `Article`, а вот потом можно будет ей добавлять типы, категории и т.д.

2019-02-19 11:18 UTC, GeorgeSokolovsky commented on src/news/news.service.ts
> +    constructor(@InjectModel('News') private readonly newsModel: Model<News>) {}
Соответственно будет меняться и все связанное с сущностью в ПР-е

2019-02-19 11:18 UTC, GeorgeSokolovsky commented on src/news/news.module.ts
> +    imports: [MongooseModule.forFeature([{name: 'News', schema: NewsSchema}])],
Вынеси имя сущности в константу, в нескольких файлах используется

2019-02-19 11:18 UTC, GeorgeSokolovsky commented on src/news/dto/CreateNewsDto.ts
> +export class CreateNewsDto {
@KKurchavy такой формат фронт устраивает?

2019-02-19 11:18 UTC, GeorgeSokolovsky commented on .gitignore
> +db.config.json
Я за то, чтобы сделать один файл конфигов `config.json`, а в нем секцию db уже. Это будет удобнее в связке с `ConfigService`

2019-02-19 12:44 UTC, GeorgeSokolovsky requested changes

2019-02-19 12:44 UTC, GeorgeSokolovsky commented on config.json
> +    "dbProperties": {
может просто `db`?

2019-02-19 12:44 UTC, GeorgeSokolovsky commented on config.json
> +{
И файл под gitignore

2019-02-19 12:44 UTC, GeorgeSokolovsky commented on src/app.module.ts
> +
Лишняя строка

2019-02-19 12:44 UTC, GeorgeSokolovsky commented on src/article/article.module.ts
> +    imports: [MongooseModule.forFeature([{name: ENTITY_NAME, schema: ArticleSchema}])],
`ARTICLE_MODEL`?

2019-02-19 12:44 UTC, GeorgeSokolovsky commented on src/article/schemas/article.schema.ts
> +export const ArticleSchema = new Schema({
Добавь автоматическое создание `createdAt`, `updatedAt`

2019-02-19 13:06 UTC, GeorgeSokolovsky requested changes

2019-02-19 13:06 UTC, GeorgeSokolovsky commented on src/article/schemas/article.schema.ts
> +    createdAt: new Date(),
Не руками, монгус сам умеет, https://mongoosejs.com/docs/guide.html#timestamps

2019-02-19 13:06 UTC, GeorgeSokolovsky commented on config.json
> +{
Надо убрать этот файл из ПР-а

2019-02-19 15:59 UTC, GeorgeSokolovsky requested changes

2019-02-19 15:59 UTC, GeorgeSokolovsky commented on src/article/article.controller.spec.ts
> +describe('ArticleController e2e', () => {
Вот такие тесты пока лишние, мы позже попробуем их писать, но более осознанно.

2019-02-19 16:11 UTC, KKurchavy approved these changes

2019-02-20 06:43 UTC, GeorgeSokolovsky approved these changes

2019-02-20 06:43 UTC, merged